[package]
name = "netpong-rs"
version = "0.1.0"
authors = ["Victor Hermann Chiletto <victor.vasconceloschiletto@gmail.com>"]

[dependencies]
ggez = "0.4"
prost = "^0.4.0"
prost-derive = "^0.4.0"
bytes = "^0.4.10"


[build-dependencies]
prost-build = "^0.4.0"

